accounts/urls.py
from django.urls import path

#app_name = 'accounts'

urlpatterns = [
    #base_views.py
]

home/urls.py
from django.urls import path

from .views import base_views

app_name = 'home'

urlpatterns = [
    #base_views.py
    path('', base_views.index, name='index'),
]

trade_journal/urls.py
from django.urls import path

from .views import base_views

app_name = 'trade_journal'

urlpatterns = [
    #base_views.py
    path('', base_views.index, name='index'),
]

home/models.py
from django.db import models

# Create your models here.

trade_journal/models.py
from django.db import models
from django.contrib.auth.models import User

class TradeJournal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    #매매일지
    transaction_text = models.JSONField('매매일지',encoder=None, default=dict)

    #결과
    result_text = models.JSONField('결과',encoder=None, default=dict)

    #거래소
    currency = models.CharField('거래소',max_length=20, default='')

    #심볼 
    symbol = models.CharField('심볼',max_length=20, default='')

    #작성일은 제목과 동일
    created_at = models.DateTimeField('작성일', auto_now_add=True)
    updated_at = models.DateTimeField('갱신일', auto_now=True)

accounts/views/views.py
from django.shortcuts import render

# Create your views here.

home/views/base_views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'home/home.html')

trade_journal/views/base_views.py
from django.shortcuts import render
from ..models import TradeJournal
from datetime import datetime, date, timedelta

def index(request):
    #처음과 끝 시간 
    start_end_date_list =[TradeJournal.objects.values('created_at').earliest('created_at'),TradeJournal.objects.values('created_at').latest('created_at')]

    sort_value = 'newest' if request.GET.get('sort') == None else request.GET.get('sort')
    currency_value = 'all' if request.GET.get('currency') == None else request.GET.get('currency')
    symbol_value = 'all' if request.GET.get('symbol') == None else request.GET.get('symbol')

    date_range_value = '날짜 선택' if request.GET.get('date_range') == None else request.GET.get('date_range')
    # date_range_value값 date로 변경
    date_range = None
    if date_range_value != '날짜 선택':
        date_range = date_range_value.split(' - ')
        date_range[0] = datetime.strptime(date_range[0], '%Y/%m/%d').date()
        date_range[1] = datetime.strptime(date_range[1], '%Y/%m/%d').date()

    # 코인종류 선택시 filter

      # 심볼 filter
    currency_list = TradeJournal.objects.values('currency').distinct('currency') if symbol_value == 'all' else TradeJournal.objects.values('currency').distinct('currency').filter(symbol=symbol_value)
      #  날짜 범위 필터
    currency_list = currency_list if date_range_value == "날짜 선택" else currency_list.filter(created_at__range=[date_range[0],date_range[1] + timedelta(days=1)])

    # 거래소선택시 filter

      # 심볼 filter
    symbol_list = TradeJournal.objects.values('symbol').distinct('symbol') if currency_value == 'all' else TradeJournal.objects.values('symbol').distinct('symbol').filter(currency=currency_value)
      #  날짜 범위 필터
    symbol_list = symbol_list if date_range_value == "날짜 선택" else symbol_list.filter(created_at__range=[date_range[0],date_range[1] + timedelta(days=1)])


    # 로그인 되어있으면
    if request.user.is_authenticated:
        # 날짜순 정렬
        journal_list = TradeJournal.objects.order_by('-created_at') if sort_value == 'newest' else TradeJournal.objects.order_by('created_at')

        # 거래소별 정렬
        journal_list = journal_list if currency_value == 'all' else journal_list.filter(currency=currency_value)

        # 코인별 정렬
        journal_list = journal_list if symbol_value == 'all' else journal_list.filter(symbol=symbol_value)

        # 날짜범위 정렬
        journal_list = journal_list if date_range_value == '날짜 선택' else journal_list.filter(created_at__range=[date_range[0],date_range[1] + timedelta(days=1)])

        context = {
                   'start_end_date_list':start_end_date_list,
                   'journal_list': journal_list,
                   'sort_value': sort_value,
                   'currency_list': currency_list,
                   'currency_value': currency_value,
                   'symbol_list': symbol_list,
                   'symbol_value': symbol_value,
                   'date_range_value':date_range_value,
                   'date_range':date_range,
                  }

        return render(request, 'trade_journal/index.html', context)
    else:
        #매매일지 소개페이지 작성
        pass

    return render(request, 'trade_journal/index.html')

templates/advanced_chart.html
   <!-- TradingView Widget BEGIN -->
    <div class="tradingview-widget-container">
        <div id="tradingview"></div>
        <div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/symbols/NASDAQ-AAPL/" rel="noopener" target="_blank"><span class="blue-text">AAPL Chart</span></a> by TradingView</div>
    </div>
        <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
        <script type="text/javascript">
            const theme_button = document.querySelector('.mode-change-btn') 
            document.addEventListener('DOMContentLoaded', () => {
                advanced_chart();
                }
            )

            theme_button.addEventListener('click', () => {
                advanced_chart();
            });            


            function advanced_chart(){
                let theme = document.getElementById("theme").getAttribute("data-bs-theme");
                const widget = new TradingView.widget(
                    {
                        "width": 980,
                        "height": 610,
                        "symbol": "NASDAQ:AAPL",
                        "interval": "D",
                        "timezone": "Etc/UTC",
                        "theme": theme,
                        "style": "1",
                        "locale": "en",
                        "toolbar_bg": "#f1f3f6",
                        "enable_publishing": false,
                        "allow_symbol_change": true,
                        // ==================== BEGIN ====================
                        "studies": [
                            {
                                id: "MASimple@tv-basicstudies",
                                // This sets the period
                                inputs: {
                                    length: 200,
                                },
                            },
                            {
                                id: "RSI@tv-basicstudies",
                                inputs: {
                                    length: 4
                                 }
                             },
                             {
                                 id: "MAExp@tv-basicstudies",
                                 inputs: {
                                     length: 4
                                 }
                             },
                             {
                                 id: "MAExp@tv-basicstudies",
                                 inputs: {
                                     length: 12
                                 }
                             },
                             {
                                 id: "ATR@tv-basicstudies",
                             },

                         ],
                         // ====================  END  ====================
                         "container_id": "tradingview"
                   }
               );            
            }

        </script>
    <!-- TradingView Widget END -->

templates/base.html
{% load static %}

<!doctype html>
<html lang="ko" style="height: 100%; margin: 0;" data-bs-theme="light" id="theme">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <!-- jQuery CSS,JS-->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <!-- OMC CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'date_range_picker.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'dark.css' %}">


    <title>One More Coin</title>
    <style type="text/css">
        @font-face {
            font-family: "Pretendard-Regular";
            src: url("https://cdn.jsdelivr.net/gh/Project-Noonnu/noonfonts_2107@1.1/Pretendard-Regular.woff")
            format("woff");
            font-weight: 400;
            font-style: normal;
            }
        body {font-family: "Pretendard-Regular";}
    </style>
</head>
<body class="m-0 min-vh-100">

<!-- 네비게이션바 -->
{% include "navbar.html" %}

<script src="{% static 'function.js' %}"></script>
{% block content %}
{% endblock %}

{% include "footer.html" %}

</body>
</html>

templates/base_login.html
{% load static %}
<!doctype html>
<html lang="ko" style="height: 100%; margin: 0;" data-bs-theme="light">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>One More Coin</title>
    <link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable.min.css" />
    <style type="text/css">
        @font-face {
            font-family: "Pretendard-Regular";
            src: url("https://cdn.jsdelivr.net/gh/Project-Noonnu/noonfonts_2107@1.1/Pretendard-Regular.woff")
            format("woff");
            font-weight: 400;
            font-style: normal;
            }
        body {font-family: "Pretendard-Regular";}
    </style>
</head>
<!-- 네비게이션바 -->
{% include "navbar_login.html" %}
<body class="bg-white text-dark m-0 min-vh-100">
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script src="{% static 'function.js' %}"></script>

</body>
</html>

templates/footer.html
{% load static %}

<div class="container">
  <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top">
    <div class="col mb-3">
      <a href="/" class="d-flex align-items-center mb-3 link-body-emphasis text-decoration-none text-white">
        <img class="w-75" src={% static 'img/logo/logo.png' %}>
      </a>
      <p class="text-secondary">&copy; 2024</p>
    </div>

    <div class="col mb-3"></div>
    <div class="col mb-3">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">About</a></li>
      </ul>
    </div>

    <div class="col mb-3">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">About</a></li>
      </ul>
    </div>

    <div class="col mb-3">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-secondary">About</a></li>
      </ul>
    </div>
  </footer>
</div>

templates/home/home.html
{% extends "base.html" %}
{% block content %}
<div class="container min-vh-100">
</div>
{% endblock %}

templates/navbar.html
{% load static %}

<header class="p-2 border-bottom">
  <div class="container-fluid">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 link-body-emphasis text-decoration-none">
        <img class="w-75" src={% static 'img/logo/logo.png' %}>
      </a>
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0 fs-5 fw-bold">
        <li><a href="{% url 'trade_journal:index' %}" {% if request.url|slice:"0:1" == "/journal" %} class="nav-link px-2 text-dark" {% else %} class="nav-link px-2 text-black-50" {% endif %}>매매일지</a></li>
        <li><a href="#" {% if request.url|slice:"0:1" == "/journal" %} class="nav-link px-2 text-dark" {% else %} class="nav-link px-2 text-black-50" {% endif %}>자동매매</a></li>
        <li><a href="#" {% if request.url|slice:"0:1" == "/journal" %} class="nav-link px-2 text-dark" {% else %} class="nav-link px-2 text-black-50" {% endif %}>백테스팅</a></li>
        <li><a href="#" {% if request.url|slice:"0:1" == "/journal" %} class="nav-link px-2 text-dark" {% else %} class="nav-link px-2 text-black-50" {% endif %}>포트폴리오</a></li>
      </ul>
      <div class="text-end">
        <button class="mode-change-btn btn bg-transparent"><i class="bi bi-sun h4"></i></button>
        {% if user.is_authenticated %}
          <button type="button" class="btn btn-outline-dark btn-sm" onclick="location.href= '{% url 'account_logout' %}'">로그아웃</button>
        {% else %}
          <button type="button" class="btn btn-outline-dark me-2 btn-sm" onclick="location.href= '{% url 'account_login' %}'">로그인</button>
          <button type="button" class="btn btn-outline-dark btn-sm" onclick="location.href= '{% url 'account_signup' %}'">회원가입</button>
        {% endif %}
      </div>
    </div>
  </div>
</header>

templates/navbar_login.html
{% load static %}

<header class="p-2 text-bg-dark border-bottom">
  <div class="container-fluid">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-5 link-body-emphasis text-decoration-none">
        <img class="w-75" src={% static 'logo.png' %}>
      </a>
    </div>
  </div>
</header>

templates/trade_journal/index.html
{% extends "base.html" %}
{% block content %}
<div class="container min-vh-100 my-4">
    <h2>매매일지</h2>
   
    <form class="my-2" action="{% url 'trade_journal:index' %}" method="GET" id="sort">
        <div class="float-start my-3 me-3">
            <select class="form-select d-inline h-100" name="sort" id="sort" aria-label="Default select example" style="width:auto;">
                <option value="newest">최신순</option>
                <option value="oldest">오래된순</option>
            </select>

            <div id="date_range_picker" class="form-select border rounded d-inline-flex h-100" style="width:auto; align-items: center;">
                <i class="bi bi-calendar-minus me-2"></i>
                <span>날짜 선택</span>
                <input type="hidden" name="date_range" id="date_range" value="날짜 선택"/>
            </div>
        </div>

        <table class="table table-hover my-3 border text-center">
            <thead>
            <tr class="align-middle">
                <th>#</th>
                <th>제목</th>
                <th>거래소
                    {% if journal_list %}
                    <select class="form-select col mx-2 d-inline" name="currency" id="currency" aria-label="Default select example" style="width:auto;">
                        <option value='all'}>전체</option>
                        {% for currency in currency_list %}
                            <option value={{currency.currency}}>{{currency.currency}}</option>
                        {% endfor %}
                    </select>
                    {% endif %}
                </th>
                <th>코인종류
                    {% if journal_list %}
                    <select class="form-select col mx-2 d-inline" name="symbol" id="symbol" aria-label="Default select example" style="width:auto;">
                        <option value='all'}>전체</option>
                        {% for symbol in symbol_list %}
                            <option value={{symbol.symbol}}>{{symbol.symbol}}</option>
                        {% endfor %}
                    </select>
                    {% endif %}
                </th>
                <th>작성일</th>
                <th>수정일</th>
            </tr>
            </thead>
            <tbody>
            {% if journal_list %}
            {% for journal in journal_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a href="#" class="text-dark text-decoration-none">{{ journal.created_at|date:'m월 d일'}} 매매일지</a>
                </td>
                <td>{{journal.currency}}</td>
                <td>{{journal.symbol}}</td>
                <td>{{journal.created_at|date:'y년 m월 d일 G:i'}}</td>
                <td>{{journal.updated_at|date:'y년 m월 d일 G:i'}}</td> 
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">매매일지가 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
    </form>
</div>
<script type="text/javascript">
   $("select[name=sort]").val("{{sort_value}}");
   $("select[name=currency]").val("{{currency_value}}");
   $("select[name=symbol]").val("{{symbol_value}}");
   $("input[name=date_range]").val("{{date_range_value}}");
   $("#date_range_picker span").html("{{date_range_value}}");

   $(document).ready(function(){
        $("select[name=sort], select[name=currency], select[name=symbol]").change(function () {
            //sort = $("select[name=sort]").val();
            //currency = $("select[name=currency]").val();
            //symbol = $("select[name=symbol]").val();
            //date_range = $("input[name=date_range]").val();
            $("#sort, #currency, #symbol #date_range").submit();

        });
    });

    console.log({{date_range.0|date:'Y/m/d'}})
    // date range picker start
    $("#date_range_picker").daterangepicker({
        {% if date_range %}
        "startDate": "{{date_range.0|date:'Y/m/d'}}",
        "endDate": "{{date_range.1|date:'Y/m/d'}}",
        {% endif %}
        "minDate": "{{start_end_date_list.0.created_at|date:'Y/m/d'}}",
        "maxDate": "{{start_end_date_list.1.created_at|date:'Y/m/d'}}", // 데이터 베이스의 시작과 끝 시간을 최대 최소 시간으로 설정
        "locale": {
            "separator": " ~ ",                     // 시작일시와 종료일시 구분자
            "format": 'YYYY-MM-DD',     // 일시 노출 포맷
            "applyLabel": "확인",                    // 확인 버튼 텍스트
            "cancelLabel": "삭제",                   // 삭제 버튼 텍스트
            "daysOfWeek": ["일", "월", "화", "수", "목", "금", "토"],
            "monthNames": ["1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월", "11월", "12월"]
        },
        "ranges": {
            "오늘": [moment(), moment()],
            "지난 7일": [moment().subtract(6, 'days'), moment()],
            "지난 1개월": [moment().subtract(1, 'months'), moment()],
            "지난 3개월": [moment().subtract(3, 'months'), moment()],
            "지난 1년": [moment().subtract(1, 'years'), moment()],
        },
        "alwaysShowCalendars": true,                 // 항상 캘린더 노출
        "autoUpdateInpute": false,                  // 날짜 자동업데이트기능 삭제
        "timePicker": false,                        // 시간 노출 여부
        "showDropdowns": true,                     // 년월 수동 설정 여부
        "autoApply": false,                         // 확인/취소 버튼 사용여부
        "singleDatePicker": false,                   // 하나의 달력 사용 여부
    });

    $("#date_range_picker").on('apply.daterangepicker', function(ev, picker) {
        $("#date_range_picker span").html(picker.startDate.format("YYYY/MM/DD") + " - " + picker.endDate.format("YYYY/MM/DD"));
        $("input[name=date_range]").val(picker.startDate.format("YYYY/MM/DD") + " - " + picker.endDate.format("YYYY/MM/DD"));
        $("#sort, #currency, #symbol #date_range").submit();
    });

    $("#date_range_picker").on('cancel.daterangepicker', function(ev, picker) {
        $("#date_range_picker span").html("날짜 선택");
        $("input[name=date_range]").val("날짜 선택");
        $("#sort, #currency, #symbol #date_range").submit();
    });
   
    $(".drp-selected").hide();

</script>
{% endblock %}